name: Publish Package to GitHub Pages

on:
  push:
    branches: [main]
    tags: 
      - 'v*'

env:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

permissions:
  contents: write
  id-token: write # Needed for PyPI OIDC if using trusted publishing


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Create and activate virtual environment
        run: |
              python -m pip install --upgrade pip build wheel
              pip install uv
              uv venv .venv
              source .venv/bin/activate

      - name: Install dependencies
        run: |
              uv pip install -r pyproject.toml  # Regular pip install
      - name: Build package
        run: |
              pip install build
              python -m build --wheel  # Generates a .whl file in dist/

      - name: Publish to PyPI 
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ env.TWINE_USERNAME }}
          password: ${{ env.TWINE_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
          skip_existing:  true # Never overwrite existing version
          verbose: true
        # run: |  
        #   pip install twine 
        #   twine upload dist/*

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Deploy the built .whl file to GitHub Pages
          keep_files: false     # Keep old versions (for version history)
          destination_dir: ${{ github.ref_name }}  # Versioned directory